import { QAReview, Reviewer, MemberFirm, User } from '@/types/qaReview';

export const mockQAReviews: QAReview[] = [
  {
    id: '1',
    memberFirmIntranetName: 'Smith & Associates LLP',
    type: 'Current Members',
    memberContact: 'john.smith@smithassoc.com',
    reviewerName: 'Sarah Johnson',
    country: 'United States',
    reviewerStatus: 'Active',
    partnerStatus: 'Approved',
    reviewPlanned: '2024-02-15',
    reviewEndDate: '2024-03-15',
    currentGrading: 'A',
    previousGrading: 'A-',
    qaReviewStatus: 'In Progress',
  },
  {
    id: '2', 
    memberFirmIntranetName: 'Global Partners Inc',
    type: 'Prospect',
    memberContact: 'mike.chen@globalpartners.com',
    reviewerName: 'David Wilson',
    country: 'Canada',
    reviewerStatus: 'Active',
    partnerStatus: '⛔',
    reviewPlanned: '2024-01-20',
    reviewEndDate: '2024-02-20',
    currentGrading: 'B+',
    previousGrading: 'B',
    qaReviewStatus: 'Completed',
  },
  {
    id: '3',
    memberFirmIntranetName: 'European Consulting Group',
    type: 'Current Members',
    memberContact: 'anna.mueller@ecg.de',
    reviewerName: 'Emma Thompson',
    country: 'Germany',
    reviewerStatus: '⛔',
    partnerStatus: 'Approved',
    reviewPlanned: '2024-03-01',
    reviewEndDate: '2024-04-01',
    currentGrading: 'A-',
    previousGrading: 'B+',
    qaReviewStatus: 'Not Started',
  },
  {
    id: '4',
    memberFirmIntranetName: 'Asia Pacific Advisors',
    type: 'Prospect',
    memberContact: 'hiroshi.tanaka@apa.jp',
    reviewerName: 'Michael Brown',
    country: 'Japan',
    reviewerStatus: 'Active',
    partnerStatus: 'Approved',
    reviewPlanned: '2024-02-28',
    reviewEndDate: '2024-03-28',
    currentGrading: 'B',
    previousGrading: 'B-',
    qaReviewStatus: 'In Progress',
  },
  {
    id: '5',
    memberFirmIntranetName: 'London Bridge Partners',
    type: 'Current Members',
    memberContact: 'james.roberts@lbp.uk',
    reviewerName: 'Lisa Anderson',
    country: 'United Kingdom',
    reviewerStatus: 'Active',
    partnerStatus: 'Approved',
    reviewPlanned: '2024-01-15',
    reviewEndDate: '2024-02-15',
    currentGrading: 'A+',
    previousGrading: 'A',
    qaReviewStatus: 'Completed',
  },
];

export const mockReviewers: Reviewer[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    status: 'Active',
    specializations: ['Financial Services', 'Risk Management'],
    assignedReviews: 8,
  },
  {
    id: '2',
    name: 'David Wilson', 
    email: 'david.wilson@company.com',
    status: 'Active',
    specializations: ['Technology', 'Healthcare'],
    assignedReviews: 12,
  },
  {
    id: '3',
    name: 'Emma Thompson',
    email: 'emma.thompson@company.com',
    status: 'Inactive',
    specializations: ['Manufacturing', 'Compliance'],
    assignedReviews: 3,
  },
];

export const mockMemberFirms: MemberFirm[] = [
  {
    id: '1',
    name: 'Smith & Associates LLP',
    intranetName: 'Smith & Associates LLP',
    country: 'United States',
    contactPerson: 'John Smith',
    email: 'john.smith@smithassoc.com',
    phone: '+1-555-0123',
    status: 'Active',
    totalReviews: 15,
  },
  {
    id: '2',
    name: 'Global Partners Inc',
    intranetName: 'Global Partners Inc',
    country: 'Canada',
    contactPerson: 'Mike Chen',
    email: 'mike.chen@globalpartners.com',
    phone: '+1-416-555-0456',
    status: 'Active',
    totalReviews: 8,
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@company.com',
    role: 'Admin',
    status: 'Active',
    lastLogin: '2024-01-15T10:30:00Z',
  },
  {
    id: '2',
    name: 'Technical Director',
    email: 'director@company.com',
    role: 'Technical Director',
    status: 'Active',
    lastLogin: '2024-01-14T15:45:00Z',
  },
];